export const IS_FILE_UPLOADED = "IS_FILE_UPLOADED";
export const IS_FACET_SELECTED = "IS_FACET_SELECTED";
export const IS_INSIGHT_SELECTED = "IS_INSIGHT_SELECTED";

export const REPORT_STATE_CHANGE = "REPORT_STATE_CHANGE";



