export const FILE_UPLOAD_CHANGE = "FILE_UPLOAD_CHANGE";
export const FACET_SELECTION_CHANGE = "FACET_SELECTION_CHANGE";
export const INSIGHT_SELECT_CHANGE = "INSIGHT_SELECT_CHANGE";

export const REPORT_STATE_CHANGE = "REPORT_STATE_CHANGE";



